name: push main

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  cloud2-push-main-defaults:
    uses: cloud2-platform/github-actions/.github/workflows/cloud2-push-main-defaults.yml@main
